---
title: "Presentations"
---

## Oral Presentations

**American Public Health Association Annual Meeting**, Minneapolis, Minnesota, October 2024, *Facilitators, Barriers, and the Trainee Experience in a Public Health Workforce Academic Training Program*

**American Public Health Association Annual Meeting**, Denver, Colorado (virtual presentation), November 2021, *Using Policy Analysis Projects to Meet Applied Practical Experience (APE) and Integrated Learning Experience (ILE) Requirements: Benefiting Community Partners Despite COVID-19 Challenges*

**American Public Health Association Annual Meeting**, Philadelphia, Pennsylvania, November 2019, *Preparing Today’s Public Health Students to Be Tomorrow’s Public Health Practitioners: Prioritizing Urban Health Needs In and Out of the Classroom*

------------------------------------------------------------------------

## Roundtable and Panel Presentations

**Teaching Prevention**, Cleveland, Ohio, March 2025, *Successfully Managing Individually Tailored Practice and Research Experiences in Public Health*

**Teaching Prevention**, Alexandria, Virginia, March 2024, *An Academic and Public Health Partnership to Achieve Public Health Training for the Northeast Ohio Workforce (PHT-NOW)* (co-presenter)

**Council on Education for Public Health Accreditation and Education Forum**, Philadelphia, Pennsylvania, November 2019, *Performing Real-World Tasks for Academic Ends*, (co-presenter)

------------------------------------------------------------------------

## Poster Presentations

**Teaching Prevention**, Cleveland, Ohio, March 2025, *The Trainee Experience in a Public Health Workforce Academic Training Program*

**Teaching Prevention**, Alexandria, Virginia, March 2024, *Lessons Learned in the Development of Individualized Practice and Research Experiences in a Medium-sized MPH Program*

**American Public Health Association Annual Meeting**, Atlanta, Georgia, November 2023, *Individually-tailored practice and research experiences in a medium-sized MPH program: The Culminating Experience as a stepping stone to professional success*

**American Public Health Association Annual Meeting**, virtual meeting, October 2020, *Analysis of 20 years of community-based research: Lessons learned and opportunities for future collaborations*
