---
title: "Research"
---

# Research Activities

Rana, A., Seeley, M., **Morris, A.** & Price, S., (2025) *Quality Metrics in Digital Health Equity: A Systematic Evaluation of Cleveland Clinic's Ongoing Virtual Care Initiative*, Ohio Journal of Public Health 7(2). doi: <https://doi.org/10.18061/ojph.v7i2.10376>

Venancius, J., Brand, R., **Morris, A.** & Mulloy, K., (2024) *Analysis of Tree Ordinances in Cuyahoga County, Ohio, and Recommendations for a Countywide Policy to Protect Trees*, Ohio Journal of Public Health 6(2), 1-22. doi: <https://doi.org/10.18061/ojph.v6i2.9848>

Prevention Research Center for Healthy Neighborhoods, Partners in Education, Evaluation, and Research (PEER) Fellow, Cohort 3, 2015-2016, *Assessing the Healthcare Needs of Refugee and Immigrant High School Students at an Urban, Multi-Cultural Public School in Cleveland*, Andrew Morris, MPH, Melanie Golembiewski, MD, MPH (unpublished)

Case Western Reserve University Master of Public Health Program, *School-Based Healthcare at a Cleveland FQHC: First Steps and Assessments* (2014, unpublished)

Case Western Reserve University Master of Public Health Program, *The Doctor Will See You (and You and You and You) Now: A Shared Medical Visit Pilot Program* (2014, unpublished)

# Advisory Committee Activity

I have served as a capstone advisory committee member for 61 students to date.
