---
title: "Teaching"
---

I teach several courses at Case Western Reserve University.

# Experiential Learning Courses

## MPHP 650: Public Health Practicum (Fall, Spring, Summer)

The Public Health Practicum is an integral component of the MPH curriculum, allowing students to apply, develop, and refine their conceptual knowledge and skills as part of a planned, supervised, and evaluated community-based experience. The Practicum is designed to move students beyond the walls of academia, to understand the political, economic, social, and organizational contexts within which public health activities are conducted. 

## MPHP 652: Public Health Capstone (Fall, Spring, Summer)

The Public Health Capstone provides students with the opportunity to apply the knowledge and skills acquired through their Master of Public Health academic program to a problem involving the health of the community. Students will learn to communicate with target groups in an effective manner; to identify ethical, social, and cultural issues relating to public health policies, research, and interventions; to identify the process by which decisions are made within the agency or organization; and to identify and coordinate use of resources at the placement site. The Capstone Essay represents the culminating experience required for the degree program and may take the form of a research thesis, an evaluation study, or an intervention study. Each student is required to formally present the experience and research findings.

## Notes

In addition to the courses above, I also lead or co-lead variations of these experiential learning courses for select dual degree programs. These include an undergraduate capstone course listing (MPHP 653) and integrated social work + public health practicum and capstone courses (MPHP 655, 656, and 657).

------------------------------------------------------------------------

# Traditional Courses

## MPHP 101: Introduction to Public Health (Spring)

MPHP 101 is a large, undergraduate course required for the minor in public health in the Department of Population & Quantitative Health Sciences. The purpose of this course is to introduce students to the science and art of public health through understanding historical and current issues through public health case histories and controversies. Students are introduced to social, behavioral, cultural, and environmental influences on population health. Emphasis is placed on social justice as a central component of public health, with an overview of health inequity and commitment to vulnerable populations. Core public health practices relating to health promotion program design, community assessment and improvement planning, health communication, health policy and enforcement, and health behavior change are featured. The course promotes understanding of health care and public health systems domestically and globally, including preparedness for and response to public health emergencies.

## PAST 451 Introduction to Public Health (Summer)

This course introduces Physician Assistant students to concepts of public health and provide experience in public health by completion of a project. The course is a relatively broad overview of the field, but focuses on 1) the intersection of public health and clinical care, and 2) public health topics that are particularly relevant in Cleveland.

------------------------------------------------------------------------

# Other

## Community Health Research & Practice (CHRP) seminar (Fall and Spring)

The Community Health Research & Practice (CHRP) seminar is held weekly and is open to all MPH students. While topics vary each week throughout the semester, the seminar has four main goals: 1) to support Master of Public Health (MPH) students as they develop and complete their Practicum experiences and Capstone projects, 2) to provide support in the development and submission of peer-reviewed presentations and publications, 3) to provide a forum for dissemination of innovations in public health practice and research, and 4) to provide a forum for networking among public health students and professionals. The CHRP seminar acts as the classroom component of community-based experiential learning requirements of the MPH program.

